Releases/v2.0.0
AusTINCANsProgrammingTeam/2023RobotCode pull request #51
Opened 2023-02-16 18:10 UTC by zbrotherton2158

# Pull Request Details

## Description
Update IDs and offsets for competition robot, read serial numbers to check robot in use
Add swerve shuffleboard functionality
Dynamic subsystem enable/disable
Assisted balance and park commands for swerve
Display control bindings on shuffleboard

## Which does this affect?

## Testing Done
Both bots - Driveteam approval on teleop handling
Competition bot - forward and curve autonomous paths tested for both alliances
Both bots - Subsystem enable/disable tested
Both bots - Swerve shuffleboard tested
Code simulated correctly
Button shuffleboard tested

## Checklist

- [x] Full system testing has been done on the robot to confirm functionality/hotfix
- [x] Pull request is coming from develop or a hotfix branch

2023-02-17 00:15 UTC, azvanderpas requested changes

2023-02-17 00:15 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/EverybotIntakeSubsystem.java
> +  private static GenericEntry intakeEntry = intakeTab.add("Intake Speed", 0.0).getEntry();
The duplicate entry in IntakeSubsystem is breaking the JUnit tests.
```suggestion
  private static GenericEntry intakeEntry = intakeTab.add("EverybotIntake Speed", 0.0).getEntry();
```

2023-02-17 00:15 UTC, azvanderpas commented on networktables.json
> +[]
Remove the git please

2023-02-17 00:15 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +  private CANSparkMax motor3;
There is no motor3

2023-02-17 00:44 UTC, caseyjbrotherton commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +}
Ironically I just asked Amadea and Josh to look at this in the update for feature/intake-subsystem.  Do we want to wait for the change to come from develop up?

2023-02-17 00:51 UTC, caseyjbrotherton commented on src/main/java/frc/robot/subsystems/SwerveSubsystem.java
> +        Logger.getInstance().recordOutput("Desired States", moduleStates);
Why are we logging like this?  Is this a string?  Is this for advantagescope?  

Would prefer numbers instead of strings.

2023-02-17 00:51 UTC, caseyjbrotherton commented on src/main/java/frc/robot/subsystems/SwerveSubsystem.java
> +        Logger.getInstance().recordOutput("Desired States", moduleStates);
and we already log desiredoutput in swervemodule

2023-02-17 00:56 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +}
Yeah, it isn't being used. Lets let it come up from develop

2023-02-17 01:23 UTC, caseyjbrotherton commented on src/main/java/frc/robot/subsystems/SwerveSubsystem.java
> +        Logger.getInstance().recordOutput("Desired States", moduleStates);
( Talked to zane, this is advantagescope required. )

2023-02-17 03:37 UTC, caseyjbrotherton commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +  private CANSparkMax motor3;
also fixed in dev already.

2023-02-21 20:06 UTC, azvanderpas approved these changes

2023-02-21 20:34 UTC, caseyjbrotherton approved these changes
approve

2023-02-21 20:53 UTC, merged