Feature/comp shuffleboard
AusTINCANsProgrammingTeam/2023RobotCode pull request #55
Opened 2023-02-18 19:43 UTC by amadeawagner

2023-02-18 20:09 UTC, caseyjbrotherton commented on src/main/java/frc/robot/subsystems/SwerveSubsystem.java
> +        };
Check in periodic and also disable the updates of these entries.

2023-02-18 20:13 UTC, caseyjbrotherton commented on src/main/java/frc/robot/subsystems/SwerveSubsystem.java
>          configTab.add(new StartEndCommand(this::coastModules, this::brakeModules, this).ignoringDisable(true).withName("Coast Modules"));
DO we need this in competition?  CHeck with Drive team ( Michael and Zane )

2023-02-18 20:17 UTC, caseyjbrotherton commented on src/main/java/frc/robot/subsystems/BuddyBalanceSubsystem.java
> +
positionEntry = line below this line....

Do we need that in competition?

2023-02-18 20:21 UTC, caseyjbrotherton requested changes
Need to check each periodic function and where all of the shuffleboard objects are referenced after initializing.  

ALso need to check and see what needs to be kept for competition in each of the subsystems.

ALso, please check OI.java as well

2023-02-22 17:01 UTC, zbrotherton2158 requested changes

2023-02-24 00:26 UTC, azvanderpas requested changes

2023-02-24 00:26 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/SwerveSubsystem.java
> +
Remove commented out lines

2023-02-24 00:26 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/SwerveSubsystem.java
> +
I think we'd want to keep at leas the headingEntry logging

2023-02-24 00:26 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> -
this file can be reverted, since there are only whitespace changes

2023-03-16 15:14 UTC, closed without merging