Features/tof switch
AusTINCANsProgrammingTeam/2023RobotCode pull request #86
Opened 2023-03-30 00:25 UTC by Asher123456789

Please switch to **Preview** and select one of the following links:

* [develop](?template=develop.md)
* [main](?template=main.md)

Once switched to the correct template, you can save the link as a bookmark. Keep in mind that switching templates will remove all already entered data within this issue.

2023-03-30 15:02 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
> +    setState(kDefaultState);
Just use the other constructor to do the common parts. Don't copy and paste methods because it makes code less maintainable. 
```suggestion
    this.intakeSubsystem = intakeSubsystem;
    this();
```

2023-03-30 23:40 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +    return new StartEndCommand(this::pull, this::stop, this).withTimeout(seconds).beforeStarting(isConeMode ? this::setConeMode : this::setCubeMode);
The beforeStarting doesn't do anything?

2023-03-30 23:42 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +  public Command pushTimed(double seconds, boolean isConeMode){
Use a different parameter name for isConeMode so it isn't confused with the class variable.

2023-03-30 23:49 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +  }
Put the breaks add the end of each case (outside of any if-blocks). Otherwise it will fall through to the next case if the conditions aren't met.

2023-03-30 23:50 UTC, azvanderpas commented on src/main/java/frc/robot/commands/ToFIntakeCommand.java
> +          break;
move out of if-else

2023-03-30 23:52 UTC, azvanderpas commented on src/main/java/frc/robot/Robot.java
Revert file before merging

2023-03-30 23:55 UTC, azvanderpas commented on src/main/java/frc/robot/RobotContainer.java
> +      subsystemEnabledLog.append(armSubsystem == null ? "Arm: Disabled" : "Arm: Enabled");
Move outside if-else block

2023-03-30 23:57 UTC, azvanderpas commented on src/main/java/frc/robot/RobotContainer.java
> +  private TimeOfFlightSensor timeOfFlightSensor = new TimeOfFlightSensor();
Need Robot.tofEnabled ternary

2023-04-01 21:42 UTC, caseyjbrotherton approved these changes, later dismissed

2023-04-01 21:52 UTC, azvanderpas requested changes

2023-04-01 21:52 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
> +    SmartDashboard.putNumber("Inverse Base", Units.radiansToDegrees(convertToBaseAngle(armXPosition, armYPosition)));
Remove debugging code

2023-04-01 21:52 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
> +  public static final Constraints kBaseConstraints = new Constraints(Units.degreesToRadians(300), Units.degreesToRadians(300));
This was source of bad high score sequence, right?

2023-04-01 21:52 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/IntakeSubsystem.java
> +    return new StartEndCommand(this::push, this::stop, this).withTimeout(seconds).beforeStarting(hasCube ? this::setConeMode : this::setCubeMode);
hasCube is incorrect logic. Revert back to coneMode

2023-04-02 14:56 UTC, azvanderpas approved these changes

2023-04-02 14:56 UTC, merged