Features/three score
AusTINCANsProgrammingTeam/2023RobotCode pull request #94
Opened 2023-04-04 19:20 UTC by zbrotherton2158

Two score needs to be merged before this PR is reviewed

2023-04-04 22:43 UTC, azvanderpas requested changes

2023-04-04 22:43 UTC, azvanderpas commented on src/main/java/frc/robot/classes/Auton.java
> +        SmartDashboard.putString("auton", autonMode.toString());
Is this for debug? If not, we should put it on a tab

2023-04-04 22:43 UTC, azvanderpas commented on src/main/java/frc/robot/classes/Auton.java
> +        configTab.add(new InstantCommand(() -> {autonCommand = getAutonSequence();}).beforeStarting(new WaitCommand(1)).withName("Load Auton").ignoringDisable(true));
Add comments about why the WaitCommand is included

2023-04-04 22:43 UTC, azvanderpas commented on src/main/java/frc/robot/classes/Auton.java
> +import edu.wpi.first.wpilibj2.command.button.Trigger;
Delete, no longer used

2023-04-04 22:43 UTC, azvanderpas commented on src/main/java/frc/robot/classes/Auton.java
> +    private Trigger modeTrigger;
Delete, no longer used

2023-04-05 00:06 UTC, azvanderpas requested changes

2023-04-05 00:06 UTC, azvanderpas commented on src/main/java/frc/robot/Robot.java
> +  public static final boolean isCompetition = false;
Revert

2023-04-05 00:06 UTC, azvanderpas commented on src/main/java/frc/robot/Robot.java
> +import edu.wpi.first.wpilibj2.command.InstantCommand;
Are these additions used?

2023-04-05 00:06 UTC, azvanderpas commented on src/main/java/frc/robot/classes/Auton.java
> +        SmartDashboard.putString("auton", autonMode.toString());
And if it is for debugging, we should removed it...

2023-04-05 00:06 UTC, azvanderpas commented on src/main/deploy/pathplanner/generatedCSV/1Score.csv
Remove the generatedCSV folder and add it to the .gitignore

2023-04-05 00:22 UTC, Shazamboo commented on src/main/deploy/pathplanner/generatedCSV/1Score.csv
done

2023-04-05 00:25 UTC, azvanderpas approved these changes

2023-04-05 00:26 UTC, merged